# Generated by Django 4.0.2 on 2022-07-11 09:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Voters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('student_id', models.CharField(max_length=50, verbose_name='Student id')),
                ('adhaar_card_no', models.CharField(max_length=50, verbose_name='Adhaar Card Number')),
                ('username', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('college_name', models.CharField(max_length=50, verbose_name='College Name')),
                ('student_id', models.CharField(max_length=50, verbose_name='Student id')),
                ('phone_number', models.CharField(max_length=50, verbose_name='Phone Number')),
                ('e_mail', models.EmailField(blank=True, max_length=50, verbose_name='E-Mail')),
                ('adhaar_card_no', models.CharField(max_length=50, verbose_name='Adhaar Card Number')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('username', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
